#!/bin/bash
echo "Checking required environment variables..."
echo ""
echo "DATABASE_URL: ${DATABASE_URL:+SET} ${DATABASE_URL:-NOT SET}"
echo "NEXTAUTH_URL: ${NEXTAUTH_URL:+SET} ${NEXTAUTH_URL:-NOT SET}"
echo "NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:+SET} ${NEXTAUTH_SECRET:-NOT SET}"
echo "GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:+SET} ${GOOGLE_CLIENT_ID:-NOT SET}"
echo "GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:+SET} ${GOOGLE_CLIENT_SECRET:-NOT SET}"
